# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6823105b89fbb2205e888043831057d160e22d39ed14d5ff58a8025376ca51c47b7f083de5e910e8b23cb86d07b6a48fc2d457c87a90bf720793af4b83a272d

test:
  secret_key_base: 6ffed39d7bbd8754716ceb1613a27a07414014426fac670a232c2051ecb6c54f0ef188840d9c2f901b3ebe93a5a3d80f9e3a19a3f51898aaa4e3649093dab38a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
